# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Aaditya Tamrakar
tagline:             'Full stack developer'
description:         'Enthusiast performance, responsive design and usability, always looking for the best project and cheese burger.'
url:                 http://aadityatamrakar.me
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Aaditya Tamrakar
  url:               https://www.facebook.com/aaditya.tamrakar.9
  email:             aaditya.span@gmail.com

# Custom vars
version:             1.0.0
